# Generated by Django 4.2.4 on 2023-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('signature', models.TextField()),
                ('hot_key', models.CharField(max_length=1000)),
                ('nominators', models.PositiveIntegerField(blank=True, null=True)),
                ('total_stake', models.FloatField(blank=True, null=True)),
                ('apy', models.FloatField(blank=True, null=True)),
                ('benefits', models.FloatField(blank=True, null=True)),
                ('tooltips', models.TextField(blank=True)),
            ],
        ),
    ]
