# Generated by Django 4.2.4 on 2023-08-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='nominators',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
