# Generated by Django 4.2.4 on 2023-08-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_delegate_nominators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='apy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='total_stake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
