# Generated by Django 4.2.4 on 2023-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_delegate_apy_alter_delegate_total_stake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='hot_key',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='key',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
