# Generated by Django 4.2.4 on 2023-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_apy_delegate_apr_delegate_emission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AprSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator", models.CharField(max_length=50)),
                ("apr", models.FloatField(blank=True, null=True)),
                ("key", models.CharField(max_length=1000)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DelegateUndelegateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=30)),
                ("action", models.CharField(max_length=50)),
                ("validator", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyAprAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator", models.CharField(max_length=50)),
                ("average_apr", models.FloatField(blank=True, null=True)),
                ("key", models.CharField(max_length=1000)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="delegate",
            name="apr_average",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
