# Generated by Django 4.2.4 on 2024-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_aprsave_delegateundelegatestatus_weeklyapraverage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegate",
            name="fees",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
